# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

#notifications
notifications:
  email:
    on_success: change
    on_failure: change

addons:
   apt:
     packages:
       - libpq-dev
