# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'


# DO NOT CHANGE THE CODE BELOW
before_install: R -q -e 'install.packages(c("remotes", "curl")); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages(); tic::before_install()'
install: R -q -e 'tic::install()'
after_install: R -q -e 'tic::after_install()'
before_script:
- R -q -e 'tic::before_script()'
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo rm -rf /usr/local/var/postgres; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then initdb /usr/local/var/postgres; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pg_ctl -D /usr/local/var/postgres start; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then createuser -s travis || true; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then createdb travis || true; fi
script: R -q -e 'tic::script()'
after_success: R -q -e 'tic::after_success()'
after_failure: R -q -e 'tic::after_failure()'
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true
after_deploy: R -q -e 'tic::after_deploy()'
after_script: R -q -e 'tic::after_script()'
# DO NOT CHANGE THE CODE ABOVE


addons
addons:
  postgresql: "9.4"
  apt:
    packages:
    - libpq-dev
    - libmagick++-dev
    - libssh2-1-dev

#jobs
matrix:
  include:
  - os: linux
    r: devel
    env:
    - DEV_VERSIONS=true
  - os: linux
    r: 3.2
  - stage: full
    os: osx
  - os: linux
    r: release
    env:
    - BUILD_PKGDOWN=true
    - R_CODECOV=true
    pandoc: true
  - os: linux
    r: 3.4
  - os: linux
    r: 3.3
  - os: linux
    env:
    - PGUSER: bogus

#notifications
notifications:
  email:
    on_success: change
    on_failure: change

# Custom parts:

#services
services:
- postgresql
