version: '3.3'
services:
  db:
    image: postgres
    container_name: "my_postgres"
    restart: always
    ports:
      - '5432:5432'
    expose:
      # Opens port 5432 on the container
      - '5432'
      # Where our data will be persisted
    volumes:
      - postgres:/var/lib/postgresql/data
# Names our volume
volumes:
  postgres:
